const reservedConstants = {
    RESERVED_WEATHER_REQUEST: 'RESERVED_WEATHER_REQUEST',
    RESERVED_WEATHER_SUCCESS: 'RESERVED_WEATHER_SUCCESS',
    RESERVED_WEATHER_FAILURE: 'RESERVED_WEATHER_FAILURE',
}

export default reservedConstants;